services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb true -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "7778:8000"
    volumes:
      - "./dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal